[build]

target = "index.html"
dist = "dist"
public_url = "/"


[serve]
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = true

[clean]
# The output dir for all final assets.
dist = "dist"
# Optionally perform a cargo clean.
cargo = false
